name: Build amat.su docker image

on:
  push:
    branches:
      - master
      - main
    paths:
      - '*'
      - 'src/**'
      - '!**.md'


jobs:
  build:
    name: Build amat.su docker image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
			- name: Clone submodule
				uses: actions/checkout@v2
				with:
					repository: remiscarlet/amat.su-secrets
					path: src/amatsu/secrets
					ssh-key: ${{ secrets.SSH_KEY }}
					persist-credentials: true
			- name: Checkout submodule
				run: |
					git submodule init
					git submodule update

