name: Build Production amat.su docker image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - 'src/**'
      - '!tf/**'
      - '!**.md'


jobs:
  build:
    name: Build amat.su docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Clone repo
        uses: actions/checkout@v2
      -
        name: Clone submodule
        uses: actions/checkout@v2
        with:
          repository: remiscarlet/amat.su-secrets
          path: src/amatsu/secrets
          ssh-key: ${{ secrets.SSH_KEY }}
          persist-credentials: true
      -
        name: Checkout submodule
        run: |
          git submodule init
          git submodule update
      -
        name: Build and push Prod
        uses: mr-smithers-excellent/docker-build-push@v5
        if: steps.extract_branch.outputs.branch == 'main'
        with:
          image: amatsu/amatsu
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.CR_PAT }}
          tags: latest
          buildArgs: IS_PROD=1
      -
        name: Build and push Dev
        uses: mr-smithers-excellent/docker-build-push@v5
        if: steps.extract_branch.outputs.branch == 'dev'
        with:
          image: amatsu/amatsu
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.CR_PAT }}
          tags: dev
          buildArgs: IS_PROD=0
