name: Build amat.su docker image

on:
  push:
    branches:
      - master
      - main
    paths:
      - '*'
      - '.github/**'
      - 'src/**'
      - '!**.md'


jobs:
  build:
    name: Build amat.su docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone repo
        uses: actions/checkout@v2
      -
        name: Clone submodule
        uses: actions/checkout@v2
        with:
          repository: remiscarlet/amat.su-secrets
          path: src/amatsu/secrets
          ssh-key: ${{ secrets.SSH_KEY }}
          persist-credentials: true
      -
        name: Checkout submodule
        run: |
          git submodule init
          git submodule update
      -
        name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: amatsu/amatsu
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.CR_PAT }}
          tags: latest
